module Bingo
  type row = Array[Integer?]
  type board = Array[row]
  type hall = Array[board]

  def bingo: (String data) -> void
  def mark_boards: (hall boards, Integer play) -> void
  def parse_boards: (Array[String] parts) -> hall
  def proof: (board board, Integer play) -> Integer
  def simulate: (Array[Integer] plays, hall boards) -> void
  def winner?: (board board) -> bool
  def winners: (hall boards) -> Array[Integer]
end
